server:
  port: 9014
spring:
  application:
    name: tensquare-article-crawler
  datasource:
    url: jdbc:mysql://47.96.175.101:3306/tensquare_article?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimeZone=Asia/Shanghai
    username: root
    password: root123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 47.96.175.101
    port: 6379
    password: 120814
    timeout: 3000
ai:
  dataPath: E:\\article